# Generated by Django 5.0 on 2023-12-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_quetions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_score', to='add_quetions.score'),
        ),
    ]
